# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wuah4sBYTA0xVw27H2gj2zuNs89WNyJH
"""

# ==============================================================================
# Causal Incentive Design Models (CIDM) - Reproducible Simulation Framework
# Requirements: PyTorch, Pandas, Scikit-Learn, Numpy, Matplotlib, SciPy
# ==============================================================================
import torch
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.stats import sem, qmc
from sklearn.kernel_ridge import KernelRidge
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import root_mean_squared_error
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', None)
device = torch.device("cpu") # CPU preferred for SciPy L-BFGS-B interoperability
print(f"Executing on: {device}")

# ------------------------------------------------------------------------------
# 1. Feature Map Generators & RKHS Sampler (M = 2D components)
# ------------------------------------------------------------------------------
def generate_rff_features(X, M, sigma, use_qmc=False, seed=42):
    """Generates finite feature map z(x) using MC or Owen-Scrambled QMC."""
    N, input_dim = X.shape
    D = M // 2
    if use_qmc:
        sobol = qmc.Sobol(d=input_dim, scramble=True, seed=seed)
        m_pow = math.ceil(math.log2(D))
        u_omega = torch.tensor(sobol.random_base2(m=m_pow)[:D], dtype=torch.float32)
        u_omega_clamped = torch.clamp(u_omega, 1e-6, 1.0 - 1e-6)
        # Map to spectral density via Inverse Normal CDF (Phi^-1)
        omega = (math.sqrt(2.0) * torch.erfinv(2.0 * u_omega_clamped - 1.0)) / sigma
        omega = omega.t()
    else:
        torch.manual_seed(seed)
        omega = torch.randn((input_dim, D), device=device) / sigma

    projection = torch.matmul(X, omega)
    Z = (1.0 / math.sqrt(D)) * torch.cat([torch.cos(projection), torch.sin(projection)], dim=1)
    return Z, omega

class RKHS_Sampler:
    """Samples standalone callable functions from the RKHS."""
    def __init__(self, M, sigma, input_dim, use_qmc):
        self.M, self.sigma, self.input_dim, self.use_qmc = M, sigma, input_dim, use_qmc
        self.seed_counter = 42

    def sample_function(self):
        dummy_X = torch.zeros((1, self.input_dim), device=device)
        _, omega = generate_rff_features(dummy_X, self.M, self.sigma, self.use_qmc, self.seed_counter)
        self.seed_counter += 1

        torch.manual_seed(self.seed_counter)
        w = torch.randn((self.M, 1), device=device)

        def f(x):
            if not isinstance(x, torch.Tensor):
                x = torch.tensor(x, dtype=torch.float32, device=device)
            if x.dim() == 1 and self.input_dim == 1:
                x = x.unsqueeze(-1)
            elif x.dim() == 1:
                x = x.unsqueeze(0)
            projection = torch.matmul(x, omega)
            Z = (1.0 / math.sqrt(self.M // 2)) * torch.cat([torch.cos(projection), torch.sin(projection)], dim=1)
            return torch.matmul(Z, w).squeeze(-1)
        return f

# ------------------------------------------------------------------------------
# 2. Environments and Analytical Baselines
# ------------------------------------------------------------------------------
def get_env_details(env_name):
    """Returns domain bounds, input dimension, and problem type."""
    details = {
        "labor": {"dim": 1, "bounds": (0.0, 5.0), "is_cost": False},
        "regulatory": {"dim": 1, "bounds": (0.0, 10.0), "is_cost": False},
        "exponential": {"dim": 1, "bounds": (0.0, 2.0), "is_cost": False},
        "groot": {"dim": 1, "bounds": (0.0, 7.0), "is_cost": True},
        "multitask": {"dim": 3, "bounds": (0.0, 3.0), "is_cost": False}
    }
    return details[env_name]

def evaluate_objectives(env_name, wF, wL):
    """Returns objectives for autograd. For Groot, returns negative cost to maximize."""
    if env_name == "labor":
        return wL - 0.5 * (wF**2).sum(dim=-1), 3.0 * wF.sum(dim=-1) - wL
    elif env_name == "regulatory":
        return 5.0 * wF.sum(dim=-1) - wL, wL - (wF**2).sum(dim=-1)
    elif env_name == "exponential":
        return wL - torch.exp(wF.sum(dim=-1)), 5.0 * wF.sum(dim=-1) - wL
    elif env_name == "groot":
        wL_clamp = torch.clamp(wL, -1.0, 4.0)
        jf_cost = wL_clamp**2 + wF.sum(dim=-1)**2 - wL_clamp * wF.sum(dim=-1)
        jl_cost = (wF.sum(dim=-1) - 5.0)**2 + wL_clamp**2
        return -jf_cost, jl_cost
    elif env_name == "multitask":
        beta = torch.tensor([2.0, 1.5, 3.0], device=device)
        return wL - 0.5 * torch.sum(wF**2, dim=-1), torch.sum(wF * beta, dim=-1) - wL

def compute_argmax_constrained(f, env_name, device, res=2000):
    """Solves Follower's Best Response via Halton Grid Search + SciPy L-BFGS-B."""
    env = get_env_details(env_name)
    dim, bnd = env["dim"], env["bounds"]

    # 1. Quasi-random Grid Search
    halton = qmc.Halton(d=dim, scramble=True)
    grid_np = halton.random(n=res)
    grid_np = bnd[0] + grid_np * (bnd[1] - bnd[0])
    grid = torch.tensor(grid_np, dtype=torch.float32, device=device)

    with torch.no_grad():
        wL_grid = f(grid).squeeze(-1)
        if env_name == "groot": wL_grid = torch.clamp(wL_grid, -1.0, 4.0)
        jF_grid, _ = evaluate_objectives(env_name, grid, wL_grid)
        best_init = grid_np[torch.argmax(jF_grid)]

    # 2. SciPy L-BFGS-B Fine-Tuning
    def objective_and_gradient(x_np):
        x_tensor = torch.tensor(x_np, dtype=torch.float32, device=device, requires_grad=True).unsqueeze(0)
        wL = f(x_tensor).squeeze(0)
        if env_name == "groot": wL = torch.clamp(wL, -1.0, 4.0)
        jF, _ = evaluate_objectives(env_name, x_tensor, wL)
        loss = -jF.sum()

        # Use torch.autograd.grad to explicitly compute gradients
        grad_x = torch.autograd.grad(loss, x_tensor)[0]

        return loss.item(), grad_x.cpu().numpy().astype(np.float64).flatten()

    scipy_bounds = [(bnd[0], bnd[1])] * dim
    result = minimize(
        fun=objective_and_gradient, x0=best_init, method='L-BFGS-B',
        jac=True, bounds=scipy_bounds, options={'ftol': 1e-9, 'disp': False}
    )
    return result.x

def compute_true_baseline(env_name, gamma_func, wF_star, sigma_wF, sigma_wL, device):
    """High-precision numerical integration (10^5 samples) over follower's structural noise."""
    env = get_env_details(env_name)
    dim, bnd = env["dim"], env["bounds"]

    eps_wF = torch.randn((100000, dim), device=device) * sigma_wF
    # Fix: Ensure wF_star is float32 to match eps_wF and omega in gamma_func
    wF_exec = torch.clamp(torch.tensor(wF_star, dtype=torch.float32, device=device) + eps_wF, bnd[0], bnd[1]).to(torch.float32)

    with torch.no_grad():
        gamma_exec = gamma_func(wF_exec)
        expected_gamma = gamma_exec.mean().item()

    wF_s = wF_star[0] if dim == 1 else wF_star
    if env_name == "labor":
        return 3.0 * wF_s - expected_gamma
    elif env_name == "regulatory":
        return expected_gamma - (wF_s**2) - (sigma_wF**2)
    elif env_name == "exponential":
        return 5.0 * wF_s - expected_gamma
    elif env_name == "groot":
        gamma_clamp = torch.clamp(gamma_exec, -1.0, 4.0)
        expected_gamma_sq = (gamma_clamp**2).mean().item()
        return (wF_s - 5.0)**2 + sigma_wF**2 + expected_gamma_sq + sigma_wL**2
    elif env_name == "multitask":
        beta = np.array([2.0, 1.5, 3.0])
        return np.dot(wF_s, beta)

# ------------------------------------------------------------------------------
# 3. Experiment Execution Loops
# ------------------------------------------------------------------------------
def get_ci(data):
    """Computes 95% Confidence Interval via Standard Error of the Mean."""
    return 1.96 * sem(data)

def run_experiment_1(S=40):
    print(f"--- Running Exp 1: Approximation Error (S={S} Trials) ---")
    sigma = 1.5
    X_1d = torch.linspace(0.0, 5.0, 200, device=device).unsqueeze(1)
    X_3d = torch.tensor(qmc.Halton(d=3).random(200), dtype=torch.float32) * 3.0

    def exact_k(X):
        X_norm = (X**2).sum(1).view(-1, 1)
        sq_dist = X_norm + X_norm.t() - 2.0 * torch.mm(X, X.t())
        return torch.exp(-sq_dist / (2 * sigma**2))

    K_1d, K_3d = exact_k(X_1d), exact_k(X_3d)
    M_values, results = [5, 25, 50, 250, 500], []

    for M in M_values:
        errs = {'mc_1d': [], 'qmc_1d': [], 'mc_3d': [], 'qmc_3d': []}
        for s in range(S):
            Z_mc_1, _ = generate_rff_features(X_1d, M, sigma, False, seed=s)
            Z_qm_1, _ = generate_rff_features(X_1d, M, sigma, True, seed=s)
            Z_mc_3, _ = generate_rff_features(X_3d, M, sigma, False, seed=s)
            Z_qm_3, _ = generate_rff_features(X_3d, M, sigma, True, seed=s)

            errs['mc_1d'].append(torch.mean((K_1d - torch.mm(Z_mc_1, Z_mc_1.t()))**2).item())
            errs['qmc_1d'].append(torch.mean((K_1d - torch.mm(Z_qm_1, Z_qm_1.t()))**2).item())
            errs['mc_3d'].append(torch.mean((K_3d - torch.mm(Z_mc_3, Z_mc_3.t()))**2).item())
            errs['qmc_3d'].append(torch.mean((K_3d - torch.mm(Z_qm_3, Z_qm_3.t()))**2).item())

        results.append({
            'M': M,
            'MC MSE (1D)': f"{np.mean(errs['mc_1d']):.4f} ± {get_ci(errs['mc_1d']):.4f}",
            'QMC MSE (1D)': f"{np.mean(errs['qmc_1d']):.4f} ± {get_ci(errs['qmc_1d']):.4f}",
            'MC MSE (3D)': f"{np.mean(errs['mc_3d']):.4f} ± {get_ci(errs['mc_3d']):.4f}",
            'QMC MSE (3D)': f"{np.mean(errs['qmc_3d']):.4f} ± {get_ci(errs['qmc_3d']):.4f}"
        })
    return pd.DataFrame(results)

def run_experiment_2(S=40):
    print(f"\n--- Running Exp 2: RMSE Convergence (S={S} Trials) ---")
    N_values = [100, 500, 1000, 2000]
    envs = ["labor", "regulatory", "exponential", "groot", "multitask"]
    sigma_wF, sigma_wL, sigma_J = 0.1, 0.2, 0.05
    final_results = []

    for env in envs:
        dim = get_env_details(env)["dim"]
        bnd = get_env_details(env)["bounds"]
        print(f"Evaluating Environment: {env.upper()}")

        eval_grid = qmc.Halton(d=dim, scramble=True).random(n=50)
        for i in range(dim): eval_grid[:, i] = bnd[i][0] + eval_grid[:, i] * (bnd[i][1] - bnd[i][0])
        eval_grid_t = torch.tensor(eval_grid, dtype=torch.float32, device=device)

        # 2x2 Ablation: MC vs QMC, FMLP vs FKRR
        for use_qmc in [False, True]:
            samp_prefix = "QMC" if use_qmc else "MC"
            rmse_fkrr = {N: [] for N in N_values}
            rmse_fmlp = {N: [] for N in N_values}

            for trial in range(S):
                sampler = RKHS_Sampler(M=100, sigma=1.5, input_dim=dim, use_qmc=use_qmc)
                X_data, y_target, v_true = [], [], []

                for _ in range(max(N_values) + 200):
                    func = sampler.sample_function()
                    with torch.no_grad():
                        X_data.append(func(eval_grid_t).cpu().numpy().flatten())

                    wF_star = compute_argmax_constrained(func, env, device)

                    eps_F = np.random.normal(0, sigma_wF, dim)
                    wF_exec = np.clip(wF_star + eps_F, [b[0] for b in bnd], [b[1] for b in bnd])
                    wF_exec_t = torch.tensor(wF_exec, dtype=torch.float32, device=device).unsqueeze(0)

                    with torch.no_grad():
                        wL_clean = func(wF_exec_t).squeeze(0).item()
                        if env == "groot": wL_clean = np.clip(wL_clean, -1.0, 4.0)
                        wL_exec = wL_clean + np.random.normal(0, sigma_wL)
                        _, jL_exec = evaluate_objectives(env, wF_exec_t, torch.tensor([wL_exec], device=device))

                    y_target.append(jL_exec.item() + np.random.normal(0, sigma_J))
                    v_true.append(compute_true_baseline(env, func, wF_star, sigma_wF, sigma_wL, device))

                X_all, y_all, v_all = np.vstack(X_data), np.array(y_target), np.array(v_true)
                X_test, y_test_true = X_all[-200:], v_all[-200:]

                for N in N_values:
                    X_train, y_train = X_all[:N], y_all[:N]

                    # 1. Train and Evaluate FKRR
                    krr = KernelRidge(alpha=0.1, kernel='rbf', gamma=0.01)
                    krr.fit(X_train, y_train)
                    rmse_fkrr[N].append(root_mean_squared_error(y_test_true, krr.predict(X_test)))

                    # 2. Train and Evaluate FMLP
                    mlp = MLPRegressor(hidden_layer_sizes=(128, 64, 32), max_iter=200, random_state=trial)
                    mlp.fit(X_train, y_train)
                    rmse_fmlp[N].append(root_mean_squared_error(y_test_true, mlp.predict(X_test)))

            for N in N_values:
                final_results.append({
                    'Environment': env.capitalize(), 'Method': f"{samp_prefix}-FKRR", 'N': N,
                    'RMSE_Mean': np.mean(rmse_fkrr[N]), 'RMSE_CI': get_ci(rmse_fkrr[N])
                })
                final_results.append({
                    'Environment': env.capitalize(), 'Method': f"{samp_prefix}-FMLP", 'N': N,
                    'RMSE_Mean': np.mean(rmse_fmlp[N]), 'RMSE_CI': get_ci(rmse_fmlp[N])
                })

    return pd.DataFrame(final_results)

from re import M

# ------------------------------------------------------------------------------
# 3. Experiment Execution Loops (Redefined for fix)
# ------------------------------------------------------------------------------
def run_experiment_2(S=40):
    print(f"\n--- Running Exp 2: RMSE Convergence (S={S} Trials) ---")
    N_values = [100, 500, 1000, 2000]
    envs = ["labor", "regulatory", "exponential", "groot", "multitask"]
    sigma_wF, sigma_wL, sigma_J = 0.1, 0.2, 0.05
    final_results = []

    for env in envs:
        dim = get_env_details(env)["dim"]
        bnd = get_env_details(env)["bounds"]
        print(f"Evaluating Environment: {env.upper()}")

        eval_grid = qmc.Halton(d=dim, scramble=True).random(n=50)
        # Fix: bnd is a tuple (min_val, max_val), not a list of tuples.
        # Apply the overall min/max bounds to each dimension of the eval_grid.
        for i in range(dim): eval_grid[:, i] = bnd[0] + eval_grid[:, i] * (bnd[1] - bnd[0])
        eval_grid_t = torch.tensor(eval_grid, dtype=torch.float32, device=device)

        # 2x2 Ablation: MC vs QMC, FMLP vs FKRR
        for use_qmc in [False, True]:
            samp_prefix = "QMC" if use_qmc else "MC"
            rmse_fkrr = {N: [] for N in N_values}
            rmse_fmlp = {N: [] for N in N_values}

            for trial in range(S):
                sampler = RKHS_Sampler(M=100, sigma=1.5, input_dim=dim, use_qmc=use_qmc)
                X_data, y_target, v_true = [], [], []

                for _ in range(max(N_values) + 200):
                    func = sampler.sample_function()
                    with torch.no_grad():
                        X_data.append(func(eval_grid_t).cpu().numpy().flatten())

                    wF_star = compute_argmax_constrained(func, env, device)

                    eps_F = np.random.normal(0, sigma_wF, dim)
                    # Fix: Apply the overall min/max bounds to the entire wF_exec array.
                    wF_exec = np.clip(wF_star + eps_F, bnd[0], bnd[1])
                    wF_exec_t = torch.tensor(wF_exec, dtype=torch.float32, device=device).unsqueeze(0)

                    with torch.no_grad():
                        wL_clean = func(wF_exec_t).squeeze(0).item()
                        if env == "groot": wL_clean = np.clip(wL_clean, -1.0, 4.0)
                        wL_exec = wL_clean + np.random.normal(0, sigma_wL)
                        _, jL_exec = evaluate_objectives(env, wF_exec_t, torch.tensor([wL_exec], device=device))

                    y_target.append(jL_exec.item() + np.random.normal(0, sigma_J))
                    v_true.append(compute_true_baseline(env, func, wF_star, sigma_wF, sigma_wL, device))

                X_all, y_all, v_all = np.vstack(X_data), np.array(y_target), np.array(v_true)
                X_test, y_test_true = X_all[-200:], v_all[-200:]

                for N in N_values:
                    X_train, y_train = X_all[:N], y_all[:N]

                    # 1. Train and Evaluate FKRR
                    krr = KernelRidge(alpha=0.1, kernel='rbf', gamma=0.01)
                    krr.fit(X_train, y_train)
                    rmse_fkrr[N].append(root_mean_squared_error(y_test_true, krr.predict(X_test)))

                    # 2. Train and Evaluate FMLP
                    mlp = MLPRegressor(hidden_layer_sizes=(128, 64, 32), max_iter=200, random_state=trial)
                    mlp.fit(X_train, y_train)
                    rmse_fmlp[N].append(root_mean_squared_error(y_test_true, mlp.predict(X_test)))

            for N in N_values:
                final_results.append({
                    'Environment': env.capitalize(), 'Method': f"{samp_prefix}-FKRR", 'N': N,
                    'RMSE_Mean': np.mean(rmse_fkrr[N]), 'RMSE_CI': get_ci(rmse_fkrr[N])
                })
                final_results.append({
                    'Environment': env.capitalize(), 'Method': f"{samp_prefix}-FMLP", 'N': N,
                    'RMSE_Mean': np.mean(rmse_fmlp[N]), 'RMSE_CI': get_ci(rmse_fmlp[N])
                })

    return pd.DataFrame(final_results)

# ------------------------------------------------------------------------------
# 4. Visualization and Execution
# ------------------------------------------------------------------------------
def plot_all_results_3x2(df_exp1, df_exp2):
    """
    Generates a 3x2 array of plots for LaTeX inclusion.
    Plot 1: Experiment 1 (Kernel Approximation Error)
    Plots 2-6: Experiment 2 (Estimation Convergence for the 5 environments)
    """
    fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(14, 16))
    axes = axes.flatten()

    # --------------------------------------------------------------------------
    # Subplot 1: Experiment 1 (Approximation Error)
    # --------------------------------------------------------------------------
    ax = axes[0]
    M_vals = df_exp1['M'].values

    # Parse the formatted string "Mean ± CI" to extract the float mean for plotting
    mc_1d = [float(str(x).split(' ± ')[0]) for x in df_exp1['MC MSE (1D)']]
    qmc_1d = [float(str(x).split(' ± ')[0]) for x in df_exp1['QMC MSE (1D)']]
    mc_3d = [float(str(x).split(' ± ')[0]) for x in df_exp1['MC MSE (3D)']]
    qmc_3d = [float(str(x).split(' ± ')[0]) for x in df_exp1['QMC MSE (3D)']]

    ax.plot(M_vals, mc_1d, color='red', linestyle='--', marker='x', label='MC (1D)')
    ax.plot(M_vals, qmc_1d, color='red', linestyle='-', marker='^', label='QMC (1D)')
    ax.plot(M_vals, mc_3d, color='blue', linestyle='--', marker='o', label='MC (3D)')
    ax.plot(M_vals, qmc_3d, color='blue', linestyle='-', marker='s', label='QMC (3D)')

    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_xlabel('Feature Dimension M (log scale)')
    ax.set_ylabel('Kernel Matrix MSE (log scale)')
    ax.set_title('Exp 1: Kernel Approximation Error')
    ax.legend(loc='upper right')
    ax.grid(True, which="both", ls="--", alpha=0.5)

    # --------------------------------------------------------------------------
    # Subplots 2-6: Experiment 2 (Five Distinct Environments)
    # --------------------------------------------------------------------------
    envs = ['Labor', 'Regulatory', 'Exponential', 'Groot', 'Multitask']

    # 4 distinct colors and styles for the 4 ablation methods
    methods = ['MC-FMLP', 'QMC-FMLP', 'MC-FKRR', 'QMC-FKRR']
    colors = ['#d62728', '#ff7f0e', '#1f77b4', '#2ca02c'] # Red, Orange, Blue, Green
    linestyles = [':', ':', '--', '-']
    markers = ['x', '^', 'o', 's']

    for i, env in enumerate(envs):
        ax = axes[i + 1] # Offset by 1 because axes[0] is Exp 1

        for m, c, ls, mk in zip(methods, colors, linestyles, markers):
            subset = df_exp2[(df_exp2['Environment'] == env) & (df_exp2['Method'] == m)]
            if not subset.empty:
                ax.errorbar(subset['N'], subset['RMSE_Mean'], yerr=subset['RMSE_CI'],
                             label=m, color=c, linestyle=ls, marker=mk, capsize=4)

        ax.set_xscale('log')
        ax.set_yscale('log')
        ax.set_xlabel('Dataset Size N (log scale)')
        ax.set_ylabel('RMSE of Causal Target (log scale)')
        ax.set_title(f'Exp 2: {env} Environment')
        ax.legend(loc='upper right')
        ax.grid(True, which="both", ls="--", alpha=0.5)

    plt.tight_layout()

    # Uncomment the line below to directly export the 3x2 grid as a high-res PDF for LaTeX
    # plt.savefig("simulation_results_3x2.pdf", format='pdf', bbox_inches='tight')

    plt.show()

# ------------------------------------------------------------------------------
# Execution Block
# ------------------------------------------------------------------------------
if __name__ == "__main__":
    df_exp1 = run_experiment_1(S=20)
    print("\nTable 1 Output (MSE ± 95% CI):")
    print(df_exp1.to_string(index=False))

    df_exp2 = run_experiment_2(S=20)
    print("\nTable 2 Output (RMSE ± 95% CI):")

    # Format strings for clean pivot presentation in the console
    df_exp2['Report'] = df_exp2.apply(lambda r: f"{r['RMSE_Mean']:.3f} ± {r['RMSE_CI']:.3f}", axis=1)
    pivot_df = df_exp2.pivot_table(index=['Environment', 'Method'], columns='N', values='Report', aggfunc='first')

    # Reorder methods for logical grouping of the 2x2 ablation in the console table
    methods_order = ['MC-FMLP', 'QMC-FMLP', 'MC-FKRR', 'QMC-FKRR']
    pivot_df = pivot_df.reindex(methods_order, level='Method')
    print(pivot_df)

    # Generate the 3x2 LaTeX-ready figure
    plot_all_results_3x2(df_exp1, df_exp2)